@Finlo.Api_HostAddress = http://localhost:5262

GET {{Finlo.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Finlo.Api_HostAddress}}/weatherforecast/
Content-Type: application/json

{
  "date": "2024-06-01T00:00:00",
  "temperatureC": 25,
  "summary": "Sunny"
}